version: '3.3'
services:
  mongo-router:
    container_name: mongo-router-rs-${ROUTER_INDEX:?err}
    image: mongo
    command: mongos --configdb "config-rs/10.0.0.3:27017,10.0.0.4:27017,10.0.0.5:27017" --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=activityrank
      - MONGO_INITDB_ROOT_PASSWORD=3mdFy42dHgh5
